/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistirRouteImport } from './routes/assistir'
import { Route as Parte2RouteImport } from './routes/parte-2'
import { Route as AssistirSlugRouteImport } from './routes/assistir.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistirRoute = AssistirRouteImport.update({
  id: '/assistir',
  path: '/assistir',
  getParentRoute: () => rootRouteImport,
} as any)
const Parte2Route = Parte2RouteImport.update({
  id: '/parte-2',
  path: '/parte-2',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistirSlugRoute = AssistirSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AssistirRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRouteWithChildren
  '/parte-2': typeof Parte2Route
  '/assistir/$slug': typeof AssistirSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRouteWithChildren
  '/parte-2': typeof Parte2Route
  '/assistir/$slug': typeof AssistirSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRouteWithChildren
  '/parte-2': typeof Parte2Route
  '/assistir/$slug': typeof AssistirSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistir' | '/parte-2' | '/assistir/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistir' | '/parte-2' | '/assistir/$slug'
  id: '__root__' | '/' | '/assistir' | '/parte-2' | '/assistir/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistirRoute: typeof AssistirRouteWithChildren
  Parte2Route: typeof Parte2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistir': {
      id: '/assistir'
      path: '/assistir'
      fullPath: '/assistir'
      preLoaderRoute: typeof AssistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parte-2': {
      id: '/parte-2'
      path: '/parte-2'
      fullPath: '/parte-2'
      preLoaderRoute: typeof Parte2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistir/$slug': {
      id: '/assistir/$slug'
      path: '/$slug'
      fullPath: '/assistir/$slug'
      preLoaderRoute: typeof AssistirSlugRouteImport
      parentRoute: typeof AssistirRoute
    }
  }
}

interface AssistirRouteChildren {
  AssistirSlugRoute: typeof AssistirSlugRoute
}

const AssistirRouteChildren: AssistirRouteChildren = {
  AssistirSlugRoute: AssistirSlugRoute,
}

const AssistirRouteWithChildren = AssistirRoute._addFileChildren(
  AssistirRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistirRoute: AssistirRouteWithChildren,
  Parte2Route: Parte2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
