/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AssistirRouteImport } from './routes/assistir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Parte2RouteImport } from './routes/parte-2'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminCheckoutRouteImport } from './routes/admin.checkout'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEpisodiosRouteImport } from './routes/admin.episodios'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMidiaRouteImport } from './routes/admin.midia'
import { Route as AdminNovelasRouteImport } from './routes/admin.novelas'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBuscarRouteImport } from './routes/app.buscar'
import { Route as AppMinhaListaRouteImport } from './routes/app.minha-lista'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AssistirSlugRouteImport } from './routes/assistir.$slug'
import { Route as AppNovelaSlugRouteImport } from './routes/app.novela.$slug'
import { Route as AppWatchEpisodeIdRouteImport } from './routes/app.watch.$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistirRoute = AssistirRouteImport.update({
  id: '/assistir',
  path: '/assistir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Parte2Route = Parte2RouteImport.update({
  id: '/parte-2',
  path: '/parte-2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckoutRoute = AdminCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodiosRoute = AdminEpisodiosRouteImport.update({
  id: '/episodios',
  path: '/episodios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNovelasRoute = AdminNovelasRouteImport.update({
  id: '/novelas',
  path: '/novelas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhaListaRoute = AppMinhaListaRouteImport.update({
  id: '/minha-lista',
  path: '/minha-lista',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AssistirSlugRoute = AssistirSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AssistirRoute,
} as any)
const AppNovelaSlugRoute = AppNovelaSlugRouteImport.update({
  id: '/novela/$slug',
  path: '/novela/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchEpisodeIdRoute = AppWatchEpisodeIdRouteImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/assistir': typeof AssistirRouteWithChildren
  '/login': typeof LoginRoute
  '/parte-2': typeof Parte2Route
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/episodios': typeof AdminEpisodiosRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/novelas': typeof AdminNovelasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/minha-lista': typeof AppMinhaListaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/assistir/$slug': typeof AssistirSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/novela/$slug': typeof AppNovelaSlugRoute
  '/app/watch/$episodeId': typeof AppWatchEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistir': typeof AssistirRouteWithChildren
  '/login': typeof LoginRoute
  '/parte-2': typeof Parte2Route
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/episodios': typeof AdminEpisodiosRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/novelas': typeof AdminNovelasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/minha-lista': typeof AppMinhaListaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/assistir/$slug': typeof AssistirSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/novela/$slug': typeof AppNovelaSlugRoute
  '/app/watch/$episodeId': typeof AppWatchEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/assistir': typeof AssistirRouteWithChildren
  '/login': typeof LoginRoute
  '/parte-2': typeof Parte2Route
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/episodios': typeof AdminEpisodiosRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/novelas': typeof AdminNovelasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/minha-lista': typeof AppMinhaListaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/assistir/$slug': typeof AssistirSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/novela/$slug': typeof AppNovelaSlugRoute
  '/app/watch/$episodeId': typeof AppWatchEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/assistir'
    | '/login'
    | '/parte-2'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/checkout'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/episodios'
    | '/admin/home'
    | '/admin/login'
    | '/admin/midia'
    | '/admin/novelas'
    | '/admin/planos'
    | '/app/buscar'
    | '/app/minha-lista'
    | '/app/perfil'
    | '/assistir/$slug'
    | '/admin/'
    | '/app/'
    | '/app/novela/$slug'
    | '/app/watch/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistir'
    | '/login'
    | '/parte-2'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/checkout'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/episodios'
    | '/admin/home'
    | '/admin/login'
    | '/admin/midia'
    | '/admin/novelas'
    | '/admin/planos'
    | '/app/buscar'
    | '/app/minha-lista'
    | '/app/perfil'
    | '/assistir/$slug'
    | '/admin'
    | '/app'
    | '/app/novela/$slug'
    | '/app/watch/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/assistir'
    | '/login'
    | '/parte-2'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/checkout'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/episodios'
    | '/admin/home'
    | '/admin/login'
    | '/admin/midia'
    | '/admin/novelas'
    | '/admin/planos'
    | '/app/buscar'
    | '/app/minha-lista'
    | '/app/perfil'
    | '/assistir/$slug'
    | '/admin/'
    | '/app/'
    | '/app/novela/$slug'
    | '/app/watch/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AssistirRoute: typeof AssistirRouteWithChildren
  LoginRoute: typeof LoginRoute
  Parte2Route: typeof Parte2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistir': {
      id: '/assistir'
      path: '/assistir'
      fullPath: '/assistir'
      preLoaderRoute: typeof AssistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parte-2': {
      id: '/parte-2'
      path: '/parte-2'
      fullPath: '/parte-2'
      preLoaderRoute: typeof Parte2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkout': {
      id: '/admin/checkout'
      path: '/checkout'
      fullPath: '/admin/checkout'
      preLoaderRoute: typeof AdminCheckoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodios': {
      id: '/admin/episodios'
      path: '/episodios'
      fullPath: '/admin/episodios'
      preLoaderRoute: typeof AdminEpisodiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/novelas': {
      id: '/admin/novelas'
      path: '/novelas'
      fullPath: '/admin/novelas'
      preLoaderRoute: typeof AdminNovelasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buscar': {
      id: '/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minha-lista': {
      id: '/app/minha-lista'
      path: '/minha-lista'
      fullPath: '/app/minha-lista'
      preLoaderRoute: typeof AppMinhaListaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/assistir/$slug': {
      id: '/assistir/$slug'
      path: '/$slug'
      fullPath: '/assistir/$slug'
      preLoaderRoute: typeof AssistirSlugRouteImport
      parentRoute: typeof AssistirRoute
    }
    '/app/novela/$slug': {
      id: '/app/novela/$slug'
      path: '/novela/$slug'
      fullPath: '/app/novela/$slug'
      preLoaderRoute: typeof AppNovelaSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watch/$episodeId': {
      id: '/app/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/app/watch/$episodeId'
      preLoaderRoute: typeof AppWatchEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCheckoutRoute: typeof AdminCheckoutRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEpisodiosRoute: typeof AdminEpisodiosRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminNovelasRoute: typeof AdminNovelasRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCheckoutRoute: AdminCheckoutRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEpisodiosRoute: AdminEpisodiosRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminNovelasRoute: AdminNovelasRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppMinhaListaRoute: typeof AppMinhaListaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNovelaSlugRoute: typeof AppNovelaSlugRoute
  AppWatchEpisodeIdRoute: typeof AppWatchEpisodeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppMinhaListaRoute: AppMinhaListaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppNovelaSlugRoute: AppNovelaSlugRoute,
  AppWatchEpisodeIdRoute: AppWatchEpisodeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AssistirRouteChildren {
  AssistirSlugRoute: typeof AssistirSlugRoute
}

const AssistirRouteChildren: AssistirRouteChildren = {
  AssistirSlugRoute: AssistirSlugRoute,
}

const AssistirRouteWithChildren = AssistirRoute._addFileChildren(
  AssistirRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AssistirRoute: AssistirRouteWithChildren,
  LoginRoute: LoginRoute,
  Parte2Route: Parte2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
